name: stack-regression-tests-ol
on: push
jobs:
  stack-validation:
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup: Checkout'
        uses: actions/checkout@v2

      - name: 'Validate: stack customization and output files content agreement'
        run: ./test/stack/build-test.sh ol
  stack-tests:
    runs-on: ubuntu-latest
    needs: stack-validation
    steps:
      - name: 'Setup: Checkout'
        uses: actions/checkout@v2

      - name: 'Setup: Install Minikube'
        uses: manusa/actions-setup-minikube@v2.3.1
        with:
          minikube version: 'v1.11.0'
          kubernetes version: 'v1.17.0'
          github token: ${{ secrets.GITHUB_TOKEN }}
          start args: '--addons=registry --addons=ingress --insecure-registry "10.0.0.0/24"' 

      - name: 'Setup: Wait for nodes to be ready'
        run: |
          while [[ $(kubectl get nodes -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; do 
          echo "waiting for nodes" && sleep 1; 
          done

      - name: 'Setup: Install odo'
        run: | 
          sudo curl -L https://developers.redhat.com/content-gateway/rest/mirror/pub/openshift-v4/clients/odo/latest/odo-linux-amd64 -o /usr/local/bin/odo
          sudo chmod +x /usr/local/bin/odo

      - name: 'Setup: Print version info'
        run: |
          set -x
          docker version
          kubectl version
          odo version
          minikube version
          set +x

      - name: 'Setup: Install the Open Liberty operator'
        run: ./test/utils.sh installOpenLibertyOperator

      - name: 'Setup: Re-build the Liberty devfile stack'
        run: ./test/utils.sh customizeStack ol

      - name: 'Setup: Build the devfile stack image'
        run: ./test/utils.sh buildStackImage ol

      - name: 'Test: OuterLoop: Maven: Basic'
        if: success() || failure()
        run: ./test/outer-loop/basic-test.sh ol maven

      - name: 'Test: OuterLoop: Gradle: Basic'
        if: success() || failure()
        run: ./test/outer-loop/basic-test.sh ol gradle

